//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
namespace PopPrint
{
    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Profiles
    {

        private ProfilesProfile[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Profile", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProfilesProfile[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ProfilesProfile
    {

        private string nameField;

        private string popServerField;

        private string popUserNameField;

        private string popPasswordField;

        private string popPortField;

        private string popSSLField;

        private string popActionField;

        private string popDeleteField;

        private string archiveFileField;

        private string archiveLocationField;

        private string printQueueField;

        private string wCFURLField;

        private string wCFOperationField;

        private string wCFActiveField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PopServer
        {
            get
            {
                return this.popServerField;
            }
            set
            {
                this.popServerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PopUserName
        {
            get
            {
                return this.popUserNameField;
            }
            set
            {
                this.popUserNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PopPassword
        {
            get
            {
                return this.popPasswordField;
            }
            set
            {
                this.popPasswordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PopPort
        {
            get
            {
                return this.popPortField;
            }
            set
            {
                this.popPortField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PopSSL
        {
            get
            {
                return this.popSSLField;
            }
            set
            {
                this.popSSLField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PopAction
        {
            get
            {
                return this.popActionField;
            }
            set
            {
                this.popActionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PopDelete
        {
            get
            {
                return this.popDeleteField;
            }
            set
            {
                this.popDeleteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ArchiveFile
        {
            get
            {
                return this.archiveFileField;
            }
            set
            {
                this.archiveFileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ArchiveLocation
        {
            get
            {
                return this.archiveLocationField;
            }
            set
            {
                this.archiveLocationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PrintQueue
        {
            get
            {
                return this.printQueueField;
            }
            set
            {
                this.printQueueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WCF-URL", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WCFURL
        {
            get
            {
                return this.wCFURLField;
            }
            set
            {
                this.wCFURLField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WCF-Operation", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WCFOperation
        {
            get
            {
                return this.wCFOperationField;
            }
            set
            {
                this.wCFOperationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WCF-Active", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WCFActive
        {
            get
            {
                return this.wCFActiveField;
            }
            set
            {
                this.wCFActiveField = value;
            }
        }
    }
}